### ISSUE TITLE
not used

### ISSUE THREAD

**Issue by haoyuxin** [qunash/chatgpt-advanced#10]
Icon grey

**Comment by qunash** [comment]
What do you mean?

**Comment by haoyuxin** [comment]
example:https://user-images.githubusercontent.com/111065800/206351570-86f537bf-e14d-4816-aa3d-bec8c4415455.png

**Comment by qunash** [comment]
Added the following functionality: now if you click on the extension's icon in the browser bar you will be automatically directed to the website.

This is not yet published on the Chrome web store, so in order to enable it you will have to install the extension manually.

Thanks for your feedback.
