### ISSUE TITLE
The chatgtp-advanced, i.e. web-chatgpt does not work

### ISSUE THREAD

**Issue by loveplay1983** [qunash/chatgpt-advanced#100]
Dear god,

My web-chatgpt has been working around in terms of valuable data search, up until today, it is no longer feasible since the page shows only the official chatgpt interface, I could not find the button using web or get relevant real information from the network. 

![image](https://user-images.githubusercontent.com/17424567/224278549-bd58914b-a085-4133-956a-19c3d0f0b0f3.png)

**Comment by loveplay1983** [comment]
Dear god, 
I think I might found the issue after I have changed to the Firefox browser which it worked since then, I might need to take a look at my chrome browser I have just updated to the latest version.

**Comment by qunash** [comment]
You have some other chatgpt extension that shows those prompt templates, most likely it is interfering with WebChatGPT. Try disabling it and see if that works.

**Comment by loveplay1983** [comment]
> You have some other chatgpt extension that shows those prompt templates, most likely it is interfering with WebChatGPT. Try disabling it and see if that works.

Thank you so much, the issue has been solved, you saved my life!!!
