### ISSUE TITLE
Can you upgrade your crawl method to the next model: GTP-4?

### ISSUE THREAD

**Issue by Neowam** [qunash/chatgpt-advanced#107]
Can you upgrade your crawl method to the next model: GTP-4? Cause it now understands also URL's. Like e.g. "summarize: https://en.wikipedia.org/wiki/Avatar:_The_Way_of_Water"

**Comment by qunash** [comment]
GPT-4 still has no access to the internet. But the extension works as usual with the new (GPT-4) model.

**Comment by Neowam** [comment]
then try this prompt using GTP-4, and check what you will see:

Prompt "summarize: https://en.wikipedia.org/wiki/Avatar:_The_Way_of_Water"

I really makes a summary of this wiki page, when it's model is still trained till September 2021.

**Comment by Neowam** [comment]
Oh my, let it go, you are right, I thought it has access to the internet now...

**Comment by qunash** [comment]
It does not have access to the internet, it just hallucinates the answer.
