### ISSUE TITLE
Language output bar, ton disappeared from my text box in ChatGPT. 

### ISSUE THREAD

**Issue by vincentquero** [qunash/chatgpt-advanced#116]
Hello, 

I've lost the dropdown menu that allowed me to select an output language etc that was added once I downloaded the AIPRM extension on Chrome. Is it happening only to me ? How can I fix it ? The experience isn't affected quite negatively now.. 

Regards,
Vincent

**Comment by qunash** [comment]
Not sure what you mean. There's no language dropdown in WCGPT.

**Comment by micbed86** [comment]
That scam of AIPRM gets in conflict with WebChatGPT. Get rid of it.
