### ISSUE TITLE
Firefox not updated

### ISSUE THREAD

**Issue by afern247** [qunash/chatgpt-advanced#129]
I wanted to try probably the most anticipated feature (by me) which is adding prompts without internet search and it's not on Firefox.

The current version here is 3.2.x and on Firefox store is 3.1.5, can you please update it ❤️

**Comment by qunash** [comment]
Hi, is under review in the store, waiting for it to be approved and published.

**Comment by afern247** [comment]
Awesome! Thank youuuuuu!!!
