### ISSUE TITLE
Support for Firefox

### ISSUE THREAD

**Issue by FSpark** [qunash/chatgpt-advanced#13]
I have tried it, and I need to modify the manifest.json, but this is not compatible with the version here. 

Do I need to fork a version to help you upload it to Firefox AMO? Or what should I do?

**Comment by qunash** [comment]
Hi, thanks, that's a good question.

I wouldn't want to downgrade to v2 as it will be deprecated soon.
Maintaining two separate versions doesn't sound great either.

Maybe you could PR manifest v2, and a section in the `readme` explaining how to manually install the extension on Firefox (switching manifests manually)? I think that would be the optimal soultion.

**Comment by nobaraos12** [comment]
this is needed

**Comment by qunash** [comment]
#15 merged, thanks @FSpark
