### ISSUE TITLE
Allow numbers higher than 10 for “web results”

### ISSUE THREAD

**Issue by daryll-swer** [qunash/chatgpt-advanced#14]
Maybe hard limit it to 50 to avoid overwhelming the platform.

**Comment by qunash** [comment]
50 is way overkill. I think 10 is optimal, as it already can generate intial prompt of up to 1500 tokens.
A better way would be to return more relevant results from the backend. Will work in that direction.

**Comment by daryll-swer** [comment]
@qunash let me know, when it's ready to be tested. Maybe let us select the search results as well. Would be more accurate then.

**Comment by silnt-awaken** [comment]
I tried with 50 on a forked branch and can agree that 50 isn't optimal. At most I would do 15.

**Comment by daryll-swer** [comment]
The extension should make sure it never ignores the first two results from Google. In most cases, those are official sites or domains for the queried subject. Like, I tried asking about myself and the extension failed to inject the number 1 search result which is my official site. Same thing for apple.com or anything else.

**Comment by qunash** [comment]
@daryll-swer Are you using the latest update with an updated prompt?
Here's my results querying "Daryll Swerr":
![image](https://user-images.githubusercontent.com/3750161/206906065-d232ba5b-4374-4a85-a837-10b08af6f806.png)

**Comment by daryll-swer** [comment]
@qunash I'm using the Chrome store extension and auto-update is enabled. But as you can see in your own screenshot, it fails to fetch the #1 result from Google for that query which has 100% accurate info. As is the case for "What is Apple Inc?".

<img width="885" alt="image" src="https://user-images.githubusercontent.com/80836254/206906197-d3e6ae89-0328-45c1-8f44-5c3bb8331797.png">

**Comment by daryll-swer** [comment]
@qunash any updates on this? The extension still keeps ignoring top 1-3 results from Google.
