### ISSUE TITLE
With recent ChatGPT UI update, the toolbar and injected "/" disappears after first use.

### ISSUE THREAD

**Issue by nkabram** [qunash/chatgpt-advanced#154]
ChatGPT recently upated the UI and with the recent change the extension no longer works as expected. It will show up when first loading Chatgpt website, but after first use, the toolbar and script are no longer accessible in subsequent message exchanges. It will come back if you refresh the page but it will be entire new conversation.

**Comment by nkabram** [comment]
Looks like this is getting addressed in next release.

**Comment by qunash** [comment]
Already submitted a patched versions to all the web stores, it'll take some time before they're reviewed and become available.
In the meantime you can install v3.2.7 manually.
