### ISSUE TITLE
UI fix

### ISSUE THREAD

**Issue by aolko** [qunash/chatgpt-advanced#16]
Please align the controls with existing ones, this alone worsens the text selection UX, making it hard to select the bottom most text of the response.
![](https://i.imgur.com/cHpy3xM.png)

**Comment by qunash** [comment]
I think this is no longer an issue with the latest updates to the webpage UI? If you scroll all the way down this buttons should not get in the way.

**Comment by qunash** [comment]
I think this is no longer an issue with the latest updates to the webpage UI? If you scroll all the way down these buttons should not get in the way.

**Comment by fire17** [comment]
im also having same behavior

**Comment by qunash** [comment]
UI has been redesigned.
