### ISSUE TITLE
chrome扩展商店里的3.26版本安装后chatgpt页面下方会出现2个webCatGPT界面

### ISSUE THREAD

**Issue by tanghululalala** [qunash/chatgpt-advanced#160]
![image](https://user-images.githubusercontent.com/30349833/234169502-be67e7ee-1740-4a99-889b-1c806c734652.png)

**Comment by tanghululalala** [comment]
浏览器是Edge dev最新版. 
![image](https://user-images.githubusercontent.com/30349833/234169652-7cd15a35-7d72-4cfd-9b7f-10e8f0896eef.png)
如果使用edge扩展商店的3.25版本则不会出现这种情况.
出现这种问题之后,后续刷新页面就会显示正常, 但是如果用新标签再次打开chatGPT地址,则又会复现这种问题, 几乎100%复现

**Comment by qunash** [comment]
Hi, please update to the latest version (3.2.7) and see if that solves the problem.

**Comment by tanghululalala** [comment]
it's OK now, thx
