### ISSUE TITLE
Interested in the google search part

### ISSUE THREAD

**Issue by JasonFengGit** [qunash/chatgpt-advanced#17]
Hi qunash,
Is it possible that you can also open source the part of code for searching (`https://ddg-webapp-aagd.vercel.app`)? Wondering if we can make each result longer. 

: )

**Comment by spidyhackx** [comment]
yeah. that would be really helpful. 
recursively visit links, github repositories etc and gather more info.

**Comment by spidyhackx** [comment]
i just manually tried it with a markdown of a repo's docs, asked it some questions about the repo and the answers were excellent :)

**Comment by amitkarn** [comment]
Looks like it is using duckduckgo's API

**Comment by spidyhackx** [comment]
> Looks like it is using duckduckgo's API or scraping duckduckgo's results in realtime. I have made myself a solution. Happy to help anyone who needs it

hi, can you share it me please

**Comment by amitkarn** [comment]
Sure, DM me on Twitter. @amitk_karn

**Comment by huyouare** [comment]
> Looks like it is using duckduckgo's API or scraping duckduckgo's results in realtime. I have made myself a solution. Happy to help anyone who needs it

@amitkarn How did you find this out? Did you guess based on query-result comparisons?

**Comment by amitkarn** [comment]
Use this [https://pypi.org/project/duckduckgo-search/](https://pypi.org/project/duckduckgo-search/). Enjoy 😃

**Comment by qunash** [comment]
See #69

**Comment by daje0601** [comment]
Hi, 
First of all, Thanks for making such a useful extension. 
I have a question about `ddg-webapp-aagd.vercel.app.`
`ddg-webapp-aagd.vercel.app` was amazing because it was so fast. 
I'm curious about how it works so quickly, so I'd like to see the related code. 
I politely asked if you could share it.
