### ISSUE TITLE
Need Help: chatGPT UI 

### ISSUE THREAD

**Issue by Runcoco** [qunash/chatgpt-advanced#173]
After I disable webChatgpt extension in Chrome (v 113), I still have issue with chatGPT UI, which has no history thread, and no model selection . Need you help.  
![image](https://user-images.githubusercontent.com/46947090/236657836-5740b9a6-f9a8-47cf-bcba-32034a27d0a5.png)

**Comment by qunash** [comment]
Hi, this isn't a WebChatGPT issue. Something else must be causing this.

**Comment by Runcoco** [comment]
Thanks!  it is OK now. Maybe it is something change from openai.
