### ISSUE TITLE
Feature Request: Add Buttons to add preset prompts.

### ISSUE THREAD

**Issue by silnt-awaken** [qunash/chatgpt-advanced#18]
I keep having to copy and paste from other websites to have the AI pretend to be something, and feel like it would be useful right at the current screen, under the slider. I was trying to code it but I am not experienced in javascript.

**Comment by qunash** [comment]
Added Propmt Editor in the latest version -  2.0.2
See the [announcement](https://github.com/qunash/chatgpt-advanced/discussions/44)
