### ISSUE TITLE
create an xpi extension for firefox

### ISSUE THREAD

**Issue by nobaraos12** [qunash/chatgpt-advanced#22]
title

**Comment by useronegit** [comment]
That would be really cool if there was for firefox.

**Comment by nobaraos12** [comment]
> That would be really cool if there was for firefox.

it would make it easier all there is manual install shown from these videos 
https://odysee.com/$/search?q=chatgpt%20advanced%20

**Comment by qunash** [comment]
Implemented, see [readme.md](https://github.com/qunash/chatgpt-advanced/blob/main/README.md)
