### ISSUE TITLE
Minimalistic Options Please !

### ISSUE THREAD

**Issue by fire17** [qunash/chatgpt-advanced#23]
Hi there!
First of all let me say that this is one of the coolest extensions out there!
How I wish it would also scape the data from those sites, not just the headers and such, but until then...

OpenAI just released their history management, that with some other extensions, the side panel is fully packed
currently the Advanced Option take almost half of my sidebar,
If you can please, make the Advanced Options be collapsable, smaller and more minimalistic, or at least, be hidden when i toggle off "search the web". (atleast that last one) should be simple right?

Thanks a lot! and have a good one !

**Comment by qunash** [comment]
Hi, thanks for the feedback! This is a good suggestion. I will think about how the UI can be improved.

**Comment by qunash** [comment]
The UI has been made more minimalistic

**Comment by fire17** [comment]
Thanks! its much better :D
