### ISSUE TITLE
Congratulations and question about serp results

### ISSUE THREAD

**Issue by Prueba1011** [qunash/chatgpt-advanced#28]
Hi, great job with the extension. I would like to inquire if you use any free API to get the search results.

**Comment by Kxffie** [comment]
in this file (api.js) 

https://github.com/qunash/chatgpt-advanced/blob/main/api.js
it uses https://ddg-webapp-aagd.vercel.app/ for search results

**Comment by qunash** [comment]
See https://github.com/qunash/chatgpt-advanced/issues/69
