### ISSUE TITLE
Feature request: customized instructions

### ISSUE THREAD

**Issue by costaDario** [qunash/chatgpt-advanced#31]
Hi, congratulations for the wonderful idea you had in making this browser extension, is the best thing I installed since ChatGPT has been released.

I would like to customize Web ChatGPT instruction set given to ChatGPT, for three reasons:

1) I am Italian, and I would like ChatGPT to answer in Italian, and I can achieve this only if I translate  the instructions in my language (or I can leave them in English and add "Answer in Italian" line).

2) More important, sometimes I would like to make ChatGPT just shortly sum up what the Google results say. For example, let's say that I search 10 results for "Ukraine war news", and I don't want ChatGPT to say "result 1 says this, result 2 says this other, etc." but I just want to know a summary of all of the news in a few sentences: if I just could customize your extension, I could achieve this result.

3) Also, every user could share his experiences and customizations.

Thanks for reading

**Comment by SourCandy80** [comment]
Adding onto this, i figured it might be a decent idea to add a line in the response instructions that says "Do not mention you have been provided with search results in your answer" or something along the lines of that.

**Comment by qunash** [comment]
Hi, that's a great suggestion. I'm already working on adding this feature.

**Comment by qunash** [comment]
Added Propmt Editor in the latest version -  2.0.2
See the [announcement](https://github.com/qunash/chatgpt-advanced/discussions/44)
