### ISSUE TITLE
Bug: Internal text leaks into the chat, should have been hidden

### ISSUE THREAD

**Issue by rcswex** [qunash/chatgpt-advanced#32]
These text should have been hidden. As on the image, marked by red.
<img width="544" alt="bug" src="https://user-images.githubusercontent.com/61713868/211168416-560516cd-2914-407f-9c8c-99536c6e36ac.png">

Plugin version: Chrome, 1.1.1
Browser: Brave, Microsoft Edge
System: Windows 11
Language: Simplified Chinese

**Comment by qunash** [comment]
Hi, thanks for the feedback. The current behavior is intentional. This way users can see the exact prompt with the added web results.

However, I understand that some users may prefer to have the option to hide the prefixed text. I'll keep that in mind and consider adding that option in the future.
