### ISSUE TITLE
Which search engine does this repo use?

### ISSUE THREAD

**Issue by heya5** [qunash/chatgpt-advanced#34]

**Comment by heya5** [comment]
Hello, 

I see the url in this repo, `https://ddg-webapp-aagd.vercel.app/search?max_results=${numResults}&q=${query}` . Is this a public search engine like google or bing

**Comment by taishi55** [comment]
I'm also curious! Better query will lead better AI response. I'd like to know how it works. Thanks!!

**Comment by franckdpt** [comment]
I would love to know too!

**Comment by riotinri** [comment]
since it says ddg in the url we can assume it's duckduckgo

**Comment by sovattha** [comment]
I am also curious to know if we could not just query Duck duck go directly. Any reason we use a private endpoint?
Can we have the source as well?

**Comment by nevertoday** [comment]
is the a CLI or command tools to do so ?

**Comment by qunash** [comment]
See https://github.com/qunash/chatgpt-advanced/issues/69
