### ISSUE TITLE
Bring back the button to toggle the Web Search off

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [qunash/chatgpt-advanced#35]
Please
We all deserve this, and we all need this. Sometimes the web search results are not helpful or destroy the question. You must turn off this extension every time you don't want to search the web.

**Comment by qunash** [comment]
Hi, it must be a bug. Please share some more details.

1. Your browser type
2. Load the chatgpt page and share the contents of the log. You can open the console with `Ctrl+Shift+i`
3. WebChatGPT version you're using

Thanks

**Comment by acugroup** [comment]
I agree. Sometimes search results are off. I'd like to have an input box where we can enter the source manually without automatic search. 

It's a perfect companion to chat GPT. Thanks!

**Comment by qunash** [comment]
Hi, @acugroup. Already working on a patch to fix this issue, should be released soon. Thank you for the feedback!

**Comment by FleetAdmiralJakob** [comment]
> Hi, it must be a bug. Please share some more details.
> 
> 1. Your browser type
> 2. Page url on which the extension fails to load (optional)
> 3. Load the chatgpt page and share the contents of the log. You can open the console with `Ctrl+Shift+i`
> 4. WebChatGPT version you're using
> 
> Thanks

Browser: Edge Version 109.0.1518.55
URL: https://chat.openai.com/chat
Console: https://pastebin.com/pZLQ9PVv
Version: 1.1.1

**Comment by qunash** [comment]
Should be fixed now in the latest version - [2.0.2](https://github.com/qunash/chatgpt-advanced/releases/tag/v2.0.2)

**Comment by FleetAdmiralJakob** [comment]
Ehmmmm....
The problem with the button is fixed but now I have 3 rows saying the same.
![image](https://user-images.githubusercontent.com/77451351/216337086-cc99d153-912f-45fb-b5bc-32b72d4564c2.png)
