### ISSUE TITLE
Option to disable citations

### ISSUE THREAD

**Issue by bolach** [qunash/chatgpt-advanced#37]
Hi
Thanks for this extensions, it is great!
It is possible to add one option to remove citations numbers?

**Comment by Screeper11** [comment]
Second this, it takes too much time for it to write out the URLs, would be nice to have an option to disable it

**Comment by bolach** [comment]
> Second this, it takes too much time for it to write out the URLs, would be nice to have an option to disable it

Yes, even slow's down a little when chat is writing the full URL.
This option could keep enabled for everyone by default like it is right now. But for some niches or some site languages, it is not very good and it seems that are more people like me removing by "hand".

**Comment by qunash** [comment]
Added Propmt Editor in the latest version -  2.0.2
See the [announcement](https://github.com/qunash/chatgpt-advanced/discussions/44) 

You can now write your own prompt template that excludes citations.
