### ISSUE TITLE
How to change answer language? 

### ISSUE THREAD

**Issue by Tomi1444** [qunash/chatgpt-advanced#40]
I ask in polish, search in poland, but answer is in english

**Comment by qunash** [comment]
Hey, thanks for the feedback.

Added Propmt Editor in the latest version -  2.0.2
See the [announcement](https://github.com/qunash/chatgpt-advanced/discussions/44)

The extension has also been localized to several languages. I might add Polish as well.
Meanwhile, you can create a custom prompt template and instruct chatgpt to answer in Polish.
