### ISSUE TITLE
For students, researchers, and everyone else - Search operators

### ISSUE THREAD

**Issue by micbed86** [qunash/chatgpt-advanced#45]
It would be such a leap in functionality to include the option to construct custom search operators such as site: and "", allowing the user to filter the web search to just websites within domains such as .edu and .org, (or specific URLs) as well as only web results from pages that contain the "DOI:" phrase. For the time being, it does not even work well with custom prompts. It would be useful to be able to include anything like:

site:.edu AND site:.org AND "DOI:"

Optimally, it would be just two more fields in the footer bar: one for multiple <site:> operators separated by commas, and one for the "must contain" operators <""> separated by commas.

**Comment by qunash** [comment]
Hi, thanks for the feedback.
These filters are supported, but you need to type them into your query, not the prompt template.

**Comment by micbed86** [comment]
> Hi, thanks for the feedback. These filters are supported, but you need to type them into your query, not the prompt template.

I was kinda OK with that reply then... but now I use more complex prompt templates with injections of {query} into the instruction for the bot, and including things like site:.edu ruins the whole instruction.
