### ISSUE TITLE
Issue with appearance

### ISSUE THREAD

**Issue by alberto-agudo** [qunash/chatgpt-advanced#49]
It looks like the prompt below the search box is now repeated three times (I think today is the first time that it's happened to me). 

![image](https://user-images.githubusercontent.com/91462184/216083321-8d1f422c-38a2-4d1f-b4e3-4321c6edd1f6.png)

![image](https://user-images.githubusercontent.com/91462184/216083365-fc1323cc-6caa-4ef4-8441-a1abaad94428.png)

Thank you anyway for the work, it is a really useful add-on.

**Comment by alberto-agudo** [comment]
It has disappeared after loading the page from the URL and not clicking on the add-on, it doesn't seem like a consistent bug.

**Comment by iblueer** [comment]
I met the similar problem, the bar shows twice.
Version 2.0.5, on MSEdge.
![Snipaste_2023-02-16_15-54-47](https://user-images.githubusercontent.com/3581944/219303397-7be4d725-4812-4974-bede-57d0fdb4d0eb.png)

**Comment by qunash** [comment]
Fixed
