### ISSUE TITLE
Issue with page layout using extension

### ISSUE THREAD

**Issue by LemonTasteBlue** [qunash/chatgpt-advanced#64]
Hi,

I'm having an issue with the page layout while using this extension. It appears that the added `div` with information about the extension is breaking the bottom part of the page layout, which is then covering some parts of ChatGPT responses and the appearance of the extension itself (`Search on the web` button).

![image](https://user-images.githubusercontent.com/56279952/219114610-65dc0ef1-d1a8-4591-9491-bbb7f43457f0.png)

After some troubleshooting with the developer tools, I found that deleting the info box fixes the problem, and it seems to work as intended.

![image](https://user-images.githubusercontent.com/56279952/219114966-122440dc-6927-4de6-a737-4a67057e53fa.png)

Browser: Brave Nightly, Edge (ver. 110.0.1587.46)
ChatGPT variant: PLUS
Display: 1080p and 2560x1440
Dev tools logs are empty.

**Comment by LemonTasteBlue** [comment]
Great to hear that! Thank you for letting me know.

**Comment by V-Gutierrez** [comment]
I even cloned it to try to PR a fix but I saw that the release was 2.0.5 so probably the mantainer is just waiting chrome store approval then we will be automatically updated.
