### ISSUE TITLE
Layout issue.

### ISSUE THREAD

**Issue by jeffbalagosa** [qunash/chatgpt-advanced#66]
I love the extension! Here's the issue, I just recently signed up for ChatGPT Plus. It adds a model dropdown list, which causes the flexbox to be applied to your div to make them inline instead of stacked. Please take a look at the screenshot. I read another similar issue here but have yet to install any other ChatGPT extensions. So that's unlikely related. I'm very grateful for your work so far!
![image](https://user-images.githubusercontent.com/61676139/219131407-474f9047-e439-4ece-9f6d-972e6e0bf6fb.png)

**Comment by qunash** [comment]
Hi, thanks for the feedback!
Please see #64

**Comment by jeffbalagosa** [comment]
I did a manual install of the new version. It's great! Just wanted to thank you for the beautiful work!!
