### ISSUE TITLE
Please share Server-Script - stay transparency 

### ISSUE THREAD

**Issue by xstable** [qunash/chatgpt-advanced#69]
Thanks for this nice Plugin. 
Could you please provide the Server-Script / Implementation you made at your vercel-server, so that user can setup their own script for it. 
I am **not saying** that you are up to no good, but you know the maxim for the internet: **trust nobody** when it comes to your sensitive data.

I think many users would appreciate to be able to run that script at their own servers / pc's.

**Comment by spidyhackx** [comment]
Yeah, not the first time it has been asked #17 . he just ignores it. 
Probably hoarding sensitive data.
We might wanna move away from such extension.

**Comment by spidyhackx** [comment]
i just checked the network requests, not much user data tied to the prompt request(only user agent and ip). just don't know why he won't open-source it for improvements :(

**Comment by edugithub** [comment]
Yes, I wanted to contribute by adding a 'filter by domain site' functionality and I see that the search logic is out of the plugin... in the vercel-server :(

**Comment by nevertoday** [comment]
is't the any cli tools or command tools to simulate the web search result lists？

**Comment by jaigouk** [comment]
i ended up running proxy.js https://github.com/jaigouk/chatgpt-advanced

**Comment by amitkarn** [comment]
Use this [https://pypi.org/project/duckduckgo-search/](https://pypi.org/project/duckduckgo-search/). Enjoy 😃

**Comment by qunash** [comment]
Alright, I made the repo public: https://github.com/qunash/ddg-webapp

It's nothing more than just a thin wrapper around [duckduckgo-search/](https://pypi.org/project/duckduckgo-search/) python package.

My plan is to make this extension completely serverless. I've already moved to serverless URL to text extraction, next is scraping SERP from various search engines.
